# Generated by Django 5.0.6 on 2024-06-30 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Сarbohydrates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cur_sugar', models.FloatField(max_length=33.0)),
                ('carbohydrate', models.FloatField()),
                ('cur_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
